version: "2.1"
services:
  
  qbt:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ${QBT_CONFIG_PATH}:/config
      - ${QBT_DOWNLOADS_PATH}:${QBT_DOWNLOADS_PATH}
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${PLEX_SERIES_PATH}:/tv
      - ${PLEX_MOVIES_PATH}:/movies
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/:ro
      - ${CERTBOT_WWW_PATH}:/var/www/certbot/:ro
      - ${CERTBOT_CONF_PATH}:/etc/nginx/ssl/:ro
  
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ${CERTBOT_WWW_PATH}:/var/www/certbot/:rw
      - ${CERTBOT_CONF_PATH}:/etc/letsencrypt/:rw